name: Cypress tests run
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: run cypress tests with chrome
        uses: cypress-io/github-action@v4
         
        timeout-minutes: 10
        with:
          browser: chrome
      - name: Merge test results into one
        run: npm run report:merge
      - name: Generate HTML report
        run: npm run report:generate
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./public
         user_name: 'github-actions[bot]'
         user_email: 'github-actions[bot]@users.noreply.github.com'
